base_url = "https://preedence.github.io/marco/"
title = "Marco"

theme = "hallo"

compile_sass = true

build_search_index = false

[markdown]
highlight_code = false

[extra]
greeting = "Ciao!"
iam = "Io sono"
links = [
    { title = "E-Mail", url = "mailto:marco@farina.cloud", iconset = "fas", icon = "envelope" },
    { title = "GitHub", url = "https://github.com/preedence", icon = "github" },
	{ title = "LinkedIn", url = "https://www.linkedin.com/in/marcofarinait/", icon = "linkedin" },
    { title = "Telegram", url = "https://t.me/epolcyc", icon = "telegram" },
    { title = "Mastodon", url = "https://mastodon.social/@cicloalcano", icon = "mastodon" },
    { title = "Strava", url = "https://www.strava.com/athletes/creedence", icon = "strava" }
]

[extra.author]
name = "Marco"

[extra.theme]
background = "tomato"
foreground = "#FFF"
hover = "#333"
